#!/bin/bash

# Change to data directory
cd ../data

# Run ogr2ogr to convert each dataset to geojson
for name in borehole fossil measurement rock;
do ogr2ogr -f GeoJSON -t_srs EPSG:3857 $name.json $name.vrt;
done
